services:
  kaka-multimarcas:
    build: .
    container_name: kaka-multimarcas
    restart: unless-stopped

    networks:
      - proxy

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.kaka.rule=Host(`kakamultimarcas.com.br`) || Host(`www.kakamultimarcas.com.br`)"
      - "traefik.http.routers.kaka.entrypoints=websecure"
      - "traefik.http.routers.kaka.tls.certresolver=letsencrypt"

      - "traefik.http.services.kaka.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true