services:
  kaka-multimarcas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kaka-multimarcas
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.kaka.rule=Host(`kakamultimarcas.com.br`) || Host(`www.kakamultimarcas.com.br`)"
      - "traefik.http.routers.kaka.entrypoints=websecure"
      - "traefik.http.routers.kaka.tls=true"
      - "traefik.http.routers.kaka.tls.certresolver=letsencrypt"

      - "traefik.http.services.kaka.loadbalancer.server.port=80"

networks:
  traefik:
    external: true